spring.application.name=blooddonor
server.port=8081
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=SYSTEM
spring.datasource.password=adil123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true